### ISSUE TITLE
In example(s): \tableofcontents perhaps needs wrapped in frame

### ISSUE THREAD

**Issue by PeterMaxwell** [martstr/beamerthementnu#19]
There seems to be a layout problem with the TOC using the examples as-is (using Tex Live to compile).

This is the problem:

![ntnu_beamer_toc_flaw](https://user-images.githubusercontent.com/13427097/131329206-1e1ed361-774f-4ce3-8b23-bae9e0e882f8.png)

But if wrapped in a Beamer frame then it seems to resolve:

![ntnu_beamer_toc_fixed](https://user-images.githubusercontent.com/13427097/131329208-b8caed12-ba30-420a-9e7d-8c26d59575c5.png)

**Comment by kellertuer** [comment]
I never use a TOC (at least for my talks <25 minutes), so maybe, yes, there is a problem with TOCs. I will take a look. But it might only be beginning of next week that I find time.

**Comment by PeterMaxwell** [comment]
There's no hurry at all, and it's easily fixable (I think) by wrapping in a frame - just thought it was worth flagging :-)

**Comment by kellertuer** [comment]
I found the culprit – since I nearly never use a TOC in beamer, I mistakenly put it directly in the main code, where it is usually supposed to be in a frame (cf. the [beamer manual](http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf), either Sec. 3.6, p. 22, or on p. 106.

I adapted the example codes accordingly.
